FROM alpine:3.13
MAINTAINER Leonardo Loures <leonardo@exacta.inf.puc-rio.br>

## References:
# https://github.com/jazzdd86/alpine-flask
# https://github.com/publysher/docker-alpine-machine-learning
# https://pkgs.alpinelinux.org/package/edge/community/x86/py3-scikit-learn
# https://github.com/Docker-Hub-frolvlad/docker-alpine-python3/blob/master/Dockerfile
# https://github.com/Docker-Hub-frolvlad/docker-alpine-python-machinelearning/blob/master/Dockerfile

RUN \
	apk add --no-cache \
      --virtual=.build-dependencies \
      g++ gfortran file binutils \
      musl-dev python3-dev cython openblas-dev lapack-dev && \
  apk add libstdc++ openblas lapack py3-pip && \
  \
  ln -s locale.h /usr/include/xlocale.h && \
  \
  pip install --disable-pip-version-check --no-build-isolation numpy && \
  pip install --disable-pip-version-check --no-build-isolation pandas && \
  \
  # scipy 1.4.x releases are broken on Alpine due to: https://github.com/scipy/scipy/issues/11319
  #pip install --disable-pip-version-check --no-build-isolation scipy && \
  apk add --no-cache --virtual=.build-dependencies-scipy-patch patch && \
  cd /tmp && \
  SCIPY_VERSION=1.4.1 && \
  wget "https://github.com/scipy/scipy/releases/download/v$SCIPY_VERSION/scipy-$SCIPY_VERSION.tar.xz" && \
  tar -xJf "scipy-$SCIPY_VERSION.tar.xz" && \
  (cd "scipy-$SCIPY_VERSION" && wget https://patch-diff.githubusercontent.com/raw/scipy/scipy/pull/11320.patch -O - | patch -p1) && \
  pip install --disable-pip-version-check --no-build-isolation "/tmp/scipy-$SCIPY_VERSION/" && \
  rm -rf /tmp/* && \
  apk del .build-dependencies-scipy-patch
    
    
#RUN \
#	deps='python3-dev g++ gfortran lapack-dev postgresql-dev libxml2-dev libxslt-dev libffi-dev geos-dev' \
#	&& apk add --no-cache \
#			bash \
#			nginx \
#			uwsgi \
#			uwsgi-python3 \
#			lapack libstdc++ \
#			libpq \
#			libxslt \
#			geos \
#			\
#			py3-pip \
#			py3-pandas \
#			py3-scikit-learn \
#			${deps} \
#  \
#	&& pip3 install --upgrade pip \
#	&& pip3 install --no-cache \
#			flask \
#			requests \
#			openrouteservice \
#			geopy \
#			unidecode \
#			sqlalchemy \
#			marshmallow_sqlalchemy \
#			psycopg2 \
#			Scrapy \
#			APScheduler \
#			crochet \
#			boltons \
#			config-client \
#			py-eureka-client \
#			PyYAML \
#			xlrd \
#			flask_cors \
#			flask_jwt_extended \
#			geoalchemy2 \
#			Shapely \
#			XlsxWriter \
#  \
#	&& chmod 777 /run/ -R \
#	&& chmod 777 /root/ -R \
#  \
#	&& apk del ${deps} \
#	&& rm -rf /root/.cache

EXPOSE 80

COPY nginx.conf /etc/nginx/nginx.conf
COPY app.ini /app.ini

CMD nginx && uwsgi --ini /app.ini
